import {NgModule} from '@angular/core';
import {RouterModule} from '@angular/router';
import {SharedModule} from '@shared';
import {HighchartsChartModule} from 'highcharts-angular';

import {ROUTES} from './admin.routing';
import {
    ActivatedUsersCountComponent,
    ActiveInstanceSessionCountStatComponent,
    CloudLimitBoxComponent,
    FlavourCountStatComponent,
    FlavourDistributionBoxComponent,
    HeaderComponent,
    CloudHeaderComponent,
    ImageCountStatComponent,
    ImageDistributionBoxComponent,
    InstanceCountStatComponent,
    InstanceSessionCountStatComponent,
    JupyterSessionCountStatComponent,
    InstanceStatesBoxComponent,
    LatestActiveUsersBoxComponent,
    LatestInstancesBoxComponent,
    LatestSessionsBoxComponent,
    LatestJupyterSessionsBoxComponent,
} from './common';
import {
    DashboardComponent,
    FlavourNewComponent,
    FlavoursComponent,
    FlavourDeleteComponent,
    FlavourUpdateComponent,
    ImageDeleteComponent,
    ImageNewComponent,
    ImagesComponent,
    ImageUpdateComponent,
    InstanceActivate,
    InstanceCloudDetailsComponent,
    InstanceComponent,
    InstanceExperimentsComponent,
    InstanceMembersComponent,
    InstanceAttributesComponent,
    InstancesComponent,
    InstanceSessionsComponent,
    InstancesFilterComponent,
    NotificationsComponent,
    PlanNewComponent,
    PlansComponent,
    PlanUpdateComponent,
    SessionsComponent,
    SecurityGroupsOverviewComponent,
    SecurityGroupImportComponent,
    SecurityGroupFiltersComponent,
    UserSearchComponent,
    UsersComponent,
    UsersFilterComponent,
    SecurityGroupsComponent,
    SecurityGroupFilterNewComponent, SecurityGroupFilterDeleteComponent, SecurityGroupDeleteComponent
} from './components';

@NgModule({
    imports: [
        SharedModule,
        HighchartsChartModule,
        RouterModule.forChild(ROUTES),
    ],
    providers: [
        InstanceActivate,
    ],
    declarations: [
        DashboardComponent,
        InstancesComponent,
        HeaderComponent,
        CloudHeaderComponent,
        InstanceComponent,
        ImagesComponent,
        ImageNewComponent,
        ImageUpdateComponent,
        ImageDeleteComponent,
        ImageDistributionBoxComponent,
        FlavourDistributionBoxComponent,
        InstancesFilterComponent,
        PlansComponent,
        PlanNewComponent,
        PlanUpdateComponent,
        FlavoursComponent,
        FlavourDeleteComponent,
        FlavourNewComponent,
        FlavourUpdateComponent,
        SessionsComponent,
        CloudLimitBoxComponent,
        LatestInstancesBoxComponent,
        LatestSessionsBoxComponent,
        LatestJupyterSessionsBoxComponent,
        InstanceStatesBoxComponent,
        ImageCountStatComponent,
        FlavourCountStatComponent,
        InstanceCountStatComponent,
        InstanceSessionCountStatComponent,
        JupyterSessionCountStatComponent,
        ActiveInstanceSessionCountStatComponent,
        ActivatedUsersCountComponent,
        InstanceSessionsComponent,
        InstanceCloudDetailsComponent,
        InstanceExperimentsComponent,
        InstanceMembersComponent,
        InstanceAttributesComponent,
        NotificationsComponent,
        UserSearchComponent,
        LatestActiveUsersBoxComponent,
        SecurityGroupsComponent,
        SecurityGroupsOverviewComponent,
        SecurityGroupImportComponent,
        SecurityGroupFiltersComponent,
        SecurityGroupFilterNewComponent,
        SecurityGroupFilterDeleteComponent,
        SecurityGroupDeleteComponent,
        UsersComponent,
        UsersFilterComponent
    ],
    exports: [
        DashboardComponent,
    ],
    entryComponents: [
        ImageNewComponent,
        ImageDeleteComponent,
        ImageUpdateComponent,
        FlavourNewComponent,
        FlavourUpdateComponent,
        PlanNewComponent,
        PlanUpdateComponent,
        SecurityGroupImportComponent,
        SecurityGroupFilterNewComponent,
        SecurityGroupFilterDeleteComponent,
        SecurityGroupDeleteComponent
    ],
})
export class AdminModule {

}
